import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import './globals.css';
import ClientProvider from '@/components/ClientProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Sidebar */}
      <body className="flex bg-[#f7fbff] h-screen">
        <ClientProvider>
          <Sidebar />
          <main className="p-10 max-w-7xl w-full mx-auto overflow-y-auto">
            {/* Header */}
            <Header />
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
